### PR TITLE
Add generics first pass

### PR DESCRIPTION
**Pull request by alexswan10k**
A little more progress on classes covering a generic parameter.

Needs some cleanup, lots of similar looking generics calls!

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k Thanks, looks good. I started looking at sequences, still on the fence whether to do iterators, or the F# Seq we already have.

**Comment by alexswan10k** [comment]
Not sure, i guess there are arguments for both. It would be nice to unify around whatever the rust mechanic is to do enumeration (iterators), but i guess this could present a lot of other problems, namely having to write the glue code in rust, which means duplicating everything for arc and rc.

**Comment by ncave** [comment]
@alexswan10k I was starting to get worried a bit about performance, but with some profiling I was able to trim down the Fable part of the compilation time of the Rust tests from 60 sec down to 1 sec (as it should be). Turns out the default F# union `.ToString()` is really slow on hot paths.

**Comment by alexswan10k** [comment]
Good find.

**Pull request merged**
