### PR TITLE
pass by reference

### PR DESCRIPTION
**Pull request by alexswan10k**
* Pushed the equality checks a bit further to cover unions
* Added a couple of tests to break on move
* Fix by pass records by ref to function (defer on call site)

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k 
I did a minor cleanup to replace `shouldPassByRef` with `isCopyType`. I know there may be some benefit of keeping them separate, if they start differentiating a lot, but for now they looked the same (just opposite).

I also added a (commented) test in `RecordTests` that breaks if variables are moved in let bindings, haven't spent any time yet to figure out what's the best way to fix that.

Before we start tackling the `Array` module, it may be a good idea to step back and discuss what should the actual type be for arrays (and Vecs):
- `Rc<&[T]>`
- `Rc<[T]>`
- `Rc<[Cell<T>]>` or `Rc<[RefCell<T>]>` based on element type
- `Rc<Vec<T>>`
- slice (`&[T]`)
- mutable slice (`&mut [T]`), that's what we have right now, but that's temporary)

And for strings:
- `Rc<str>`
- `Rc<String>`

What do you think?

**Comment by ncave** [comment]
@alexswan10k
For arrays we want immutable borrowing with internal mutability, that kind of means `Rc<[Cell<T>]>` / `Rc<[RefCell<T>]>`, right? Strings are immutable, hence fewer choices there. What is your opinion?

**Comment by alexswan10k** [comment]
@ncave agree with this completely. `Rc<[RefCell<T>]>` seems like a good place to start unless you can use Cell I guess (underlying type implements copy). I want to just check - looking at the Array std library, it seems that everything is creating a new array, and there is no array level mutation/reordering going on. I can't work out if permute is reordering existing or creating new, but everything else is definitely creating a new array (otherwise you might need something like `Rc<RefCell<[T]>>`).

That has got me thinking about records and objects with mutability. Should all records be wrapped in a Rc<T> or perhaps a Rc<RefCell<T>> if they have at least one mutable internal variable, or reference something that has at least one mutable variable recursively? I know we are going to hit lifetime issues with a simple pass by ref anyway when we start looking at closures.

Some of this stuff we might just have to try some things and see what works. I am struggling to visualise this!

**Comment by ncave** [comment]
@alexswan10k 
>Should all records be wrapped in a Rc or perhaps a Rc<RefCell>

Yes, wrapped in `Rc`, but not `Rc<RefCell<`, as there is already internal field mutability to match the F# mutable record fields.

**Comment by alexswan10k** [comment]
Rc<Record> seems like the simplest approach to getting results, and probably requires the least inference. Perhaps, rather than passing things by reference to functions, perhaps they should just expect a wrapped Rc<Record> or equivalent, so we never need to worry about borrowed stuff going out of scope somewhere else. 

Been doing a bit of experimentation/hacking around, maybe the wrappers arent all necessary. Here is a quick example of both wrappers that pass the borrow checker. Note, there are a bunch of unwraps and binds that have to be done in a very specific order!
```
mod SingleThreadedMode {
    use std::{cell::RefCell, ops::DerefMut, rc::Rc};

    pub struct Nested {
        x: String
    }
    pub struct Test {
        string: String,
        mutableInt: RefCell<i32>,
        nested: Rc<Nested>
    }

    //this represents any function
    pub fn some_fn(item: Rc<Test>) -> Rc<Test> {
        //unwrap and mutate something
        let mut next = item.mutableInt.borrow_mut();
        *next += 1;//mutate

        //Make a new instance of a record, with some existing stuff
        Rc::new(Test {
                string: (item.string.clone() + "test").to_owned(), 
                mutableInt: RefCell::new(3),
                nested: Rc::new(Nested { x: "nested".to_owned()})
             })
    }

    pub fn TestWithRcBorrow(item: Rc<Test>) -> Rc<Test> {
        let a = some_fn(item.clone());//without clone this breaks, transfer ownership
        let b = some_fn(item.clone());
        b
    }
}

mod MultiThreadedModeMutex {
    use std::{sync::{Arc, Mutex}};

    pub struct Nested {
        x: String
    }
    pub struct Test {
        string: String,  
        mutableInt: Mutex<i32>, 
        nested: Arc<Nested>
    }

    pub fn some_fn(item: Arc<Test>) -> Arc<Test> {
        let mut next = item.mutableInt.lock().unwrap();
        *next += 1;//mutate

        Arc::new(
            Test {
                string: (item.string.clone() + "test").to_owned(), 
                nested: Arc::new(Nested { x: "nested".to_owned()}),
                mutableInt: Mutex::new(32)
            }
        )
    }

    pub fn TestWithRcBorrow(item: Arc<Test>) -> Arc<Test> {
        let a = some_fn(item.clone());
        let b = some_fn(item.clone());
        //the clone and bind has to happen outside as it does a move on the underlying thing. This might only apply to move closures
        let bToMove = b.clone();
        let handle = std::thread::spawn(move||{//move required as the closure might outlive the scope of the outside thing - probably not a problem in non-threaded closures
            //some_fn(bToMove.clone())
            let d = some_fn(bToMove.clone());//double clone, because we use bToMove twice, and cannot be sure which one is needed
            let e = some_fn(bToMove.clone());//you could technically not clone here
            ()
        });
        b
    }
}
```

I personally think the MultiThreadedModeMutex example is a good catch-all. Does this cover everything though? It seems too easy.

In summary:
* All records and reference types are wrapped in an Arc everywhere (or Rc for single thread). No pass by reference, always accept an Arc in a function and clone.
* All mutable variables declared either in classes/records or locally in scope should always be wrapped in a Mutex (or RwLock/RefCell), and then accessed by lock().unwrap(). You can actually inline this expression, just tested.
* These have to operate in pairs, so either you use Rc/RefCell and forget multithreading, or you use Arc/Mutex. You cannot mix Arc with RefCell as RefCell is not send/sync.


Longer term I imagine the solution here is to walk the AST before conversion, and follow all the symbol references to see how they are used. From this, you could infer if something is actually crossing threads, being borrowed etc, and use this to tag entities and function parameters with. When you render the final AST you could pull this extra context out of the compiler to make reasoned decisions about what type conversion/unwrapping needs to be done. Of course at this level we are pretty much writing an automated borrow checker, so I would prefer to kick this one down the road as long as possible!



### Arrays
So looks like arrays might be more fiddly than I originally envisaged.

https://newbedev.com/how-to-set-a-rust-array-length-dynamically

Looks like allocating array length dynamically is not something we can do with raw arrays, so either we use an abstraction such as the attached HeapArray, or just use Vec instead?

**Comment by ncave** [comment]
@alexswan10k

> Perhaps, rather than passing things by reference to functions, perhaps they should just expect a wrapped Rc or equivalent, so we never need to worry about borrowed stuff going out of scope somewhere else.

I agree, that was the intent from the start, as there seems to be no other way (i.e. poor man's GC). Perhaps later we can explore `rust-gc`.

> All records and reference types are wrapped in an Arc everywhere (or Rc for single thread). No pass by reference, always accept an Arc in a function and clone.

Yes, that's my understanding too.

> Can/should we have a compiler switch to jump between single and multi threaded as a first pass?

Yes, let's start with `Rc` and we can add a switch later to generate `Arc` etc. instead.

> All mutable variables declared either in classes/records or locally in scope should always be wrapped

I agree. Mutable fields already are wrapped, perhaps we need to switch the local bindings too.

> Looks like allocating array length dynamically is not something we can do with raw arrays, so either we use an abstraction such as the attached HeapArray, or just use Vec instead?

I guess `Vec` it is then. The question is, `Vec<T>` or `Vec<RefCell<T>>`. I'm leaning towards the latter.

I'm afraid until that basic infrastructure is there, there is a large chance that we will step over each other's work.
I can take a stab at it initially, or if you want to, let me know. There will be plenty of non-overlapping areas later.

**Comment by alexswan10k** [comment]
Great. As for which, honestly not sure. So you can get interior mutability directly of course:
```
        let mut v = vec! [1];
        (*v.first().unwrap()) = 44;
```
but I guess the big question here is will that make passing stuff around in isolation harder. Perhaps RefCell is therefore better, also it does not require the vec to be mutable.
It might be worth keeping in mind that whatever mechanism used to inject the mutability wrapper is the same as for all mutable vars, so all RefCells can easily be switched over to Mutexes/RwLocks etc.

Feel free to take a stab if you have a good idea where to begin, I do feel like I am a little out of my depth heh. Do let me know if there is anything I can help with though. I will see if there are any other small wins to tackle when I get time next.

**Comment by alexswan10k** [comment]
That's a good shout actually. Presumably something like:
```
        let mut v = vec! [1];
        let arr: = *v.as_slice();
```

**Pull request merged**
