### PR TITLE
Classes with self keyword

### PR DESCRIPTION
**Pull request by alexswan10k**
### Classes now work with the self keyword, so calls are no longer static.

```
Fable::Tests::ClassTests::WithInterface::new(&1).Add(&2, &1);
```

I have also implemented the associated trait "methods" pattern discussed, although this is not particularly useful yet, as interfaces are not working. Saying that, this does now enable correct Rc wrapping of the self param, which allows you to do evil things such as the mutable fluent pattern (although local mutability is not tested yet and possibly not working), or embedding self in the return payload. Tests cover a trivial fluent api.

### Interfaces
So here we have a bit of a problem. It seems that interfaces are erased (if you think about it, dynamic languages do not really need this concept in the output AST). They are probably being thrown out here https://github.com/fable-compiler/Fable/blob/f74e010217df299ed74135be308fb046a5a88283/src/Fable.Transforms/FSharp2Fable.fs#L1244 so perhaps we could do some Rust language override similar to the instance methods problem? Not really sure what we would return though in the output AST so a bit stuck.

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k I don't follow, don't we want the interface entities transformed as traits where the declared?

**Comment by alexswan10k** [comment]
Damn! This is quite annoying, interestinly you can do an atomic swap to get the old value out:

```
                let xs: Cell<Rc<str>> = Cell::from(Rc::from("abc"));
                let old = xs.replace(Rc::from("def"));
```
I wonder if we can hack around it somehow...

**Comment by alexswan10k** [comment]
Just FYI, I been trying to introduce the closure mutable capture test, and it has lead me to a bunch of problems/annoyances I think we can simplify around ident context.

I am therefore having another pass at transformLeaveContextByValue, transformLeaveContextByRef and transformType so we can hopefully have a single context of IsRefWrapped and IsCellWrapped, so you can switch whatever in and out, but more importantly compose them. At the moment you cant do a `Rc<Cell<T>>` for example. Not exactly simple, but it should make introducing wrappers conditionally far easier.

The sort of thing I would like to do in my context is scan the subtree and work out if the Cell is going out of scope (captured by closure). If it is, then we have a problem, and need to represent it as a `Rc<Cell<T>>`. If on the other hand it is only locally being mutated, we do not need the Rc. In fact, we probably don't need the cell either but let's not even start on that yet. The latter scenario is probably doable though with this infrastructure in place.

This is the seemingly inoffensive test
```
[<Fact>]
let ``Mutable capture works`` () =
    let mutable x = 0
    let incrementX () =
        x <- x + 1
        ()

    incrementX()
    x |> equal 1
```

**Comment by ncave** [comment]
@alexswan10k Sounds good to me. All I can say on the subject is that, for performance reasons, I would really like to not wrap cells in `Rc` when not absolutely needed (in this case maybe it is necessary).

**Pull request merged**
