### PR TITLE
Add unit tests, expanded interface tests, expanded array ops

### PR DESCRIPTION
**Pull request by alexswan10k**
A few small tweaks and additions:
* Add "unit" tests to prove units just work
* Add interface unit method to prove value getter trick works
* Turned on some array tests. Added a couple of placeholder implementations where these deferred to external
  * Filter
  * Map
  * Fold

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k Thanks! Array.filter will be improved once we add ResizeArray, but it's fine for now.

**Comment by ncave** [comment]
@alexswan10k Had to fix the imports to adapt to latest Fable changes. Files are now compiled in a different order, so imported mods had be inserted at crate level with `pub(crate) mod`. Also, Fable is now on .NET 6.0, just FYI.

**Comment by ncave** [comment]
@alexswan10k Had to fix the imports to adapt to latest Fable changes. Files are now compiled in a different order, so imported mods had be inserted at crate level with `pub(crate) mod`. Also, Fable is now on .NET 6.0, just FYI.

**Comment by alexswan10k** [comment]
Not to worry, will update my stack. I think crate-level importing is probably closer to how you would generally work with imports in rust anyway, so not sure this is entirely a bad thing. Nice.

**Comment by ncave** [comment]
@alexswan10k Yes, importing at root is what we want in order to avoid import modules nested in each other, I'm glad it works. Imports are still not perfect by a long shot, we still have to turn on the local name aliasing to avoid name clashing, but it works for now with our limited imports that don't clash, so perhaps it's good enough for MVP and can be worked on later post-MVP.

**Pull request merged**
