### PR TITLE
Fixes 1

### PR DESCRIPTION
**Pull request by alexswan10k**
Remove unecessary function duplication

### CODE REVIEW

**Comment by ncave** [comment]
@alexswan10k Minor leftover merge artifacts.

**Comment by alexswan10k** [comment]
there we go

**Comment by ncave** [comment]
We're moving at breakneck speed, I like it. I hope we can meet the deadline ;)

**Comment by ncave** [comment]
Thanks, seems to work. I added to an array test to make sure it keeps working for functions.

**Comment by alexswan10k** [comment]
haha yeah

For the record I am super happy with what is already working though, pretty exciting really. I know it is a long road still, but you can start to see the pieces coming together.

**Comment by ncave** [comment]
Yeah, it's the basic infrastructure and feature mapping that we have to get right, the rest is easy. I mean, maintaining acceptable performance for the generated code is not going to be always easy, and that's the whole point of the exercise.

**Comment by alexswan10k** [comment]
Indeed, so many optimizations that could be done, but at least if this basic strategy works, they can always be added in after. Getting something that passes the borrow checker and isn't clone everywhere is definitely a win if we can get it stable.

Yeah i might have a day or 2 off aha :) What shall I look at next though? I had a quick look at classes but the generated constructor thing made no sense to me. There was a missing method that just wasn't in the AST, and the other examples seem to do some magic to appear it out of thin air.

**Comment by alexswan10k** [comment]
I agree let's avoid overlapping if we can :)

That sounds good, there are probably still plenty of edge cases to iron out around records, unions etc.

By the way, i noticed you added option which is super cool, but it got me thinking. Considering that we cannot abstract Rc<T> from Arc<T>, does it make sense to push as much of the library code into F# if possible, so with a compiler switch you could generate either? I am still not sure how we solve this to be fair, it seems like there is no easy way in rust to abstract over both, and a lot of API designers suffer as a consequence. It kind of sucks that you pretty much end up with two libraries, one for parallel, one for single threaded scenarios.

**Comment by ncave** [comment]
@alexswan10k Absolutely, that's why I ported the JS sequences back to F#, that's the general trend. When possible, of course - in the case of Options, the Rust build-in option functions don't really work well with Rc, so we need have native methods that match instead (cause sometimes it's Catch22 if we do it in F#).

As for tests to work on, I see some disabled tests in ClosureTests (just sayin') ;)

**Comment by alexswan10k** [comment]
Ha indeed, looks like there are some rough edges still around Cell mutable capture. Might be some funky wrap/nowrap inference that can be done now that useages can be tracked.

Sounds good anyway.

**Comment by ncave** [comment]
@alexswan10k Added a union test that is breaking when uncommented. Perhaps `maybeUnwrapRef` needs to sometimes return DerefRef (if that's even a word, I mean `&*` instead of just `*`).

**Comment by alexswan10k** [comment]
Yeah it looks like the if let is not using prepareRefForPatternMatch. This actually calls makeAsRef which generates a .as_ref(). This is super useful because it gives you a ref of the unwrapped thing regardless if you give it a &Rc<T> or a Rc<T>.

I will have a look into this tomorrow, pretty sure this is an easy fix.

**Pull request merged**
